export const cards = [
  {
    name: "Weak Farmer",
    defaultAttack: 2,
    attack: 2,
    cost: 1,
    defaultTurns: 3,
    turns: 3,
    ability: "",
    img: "./src/img/weakFarmer2.jpeg",
    id: 1,
  },
  {
    name: "Weak Farmer",
    defaultAttack: 2,
    attack: 2,
    cost: 1,
    defaultTurns: 3,
    turns: 3,
    ability: "",
    img: "./src/img/weakFarmer2.jpeg",
    id: 2,
  },
  {
    name: "Tree of Vitality",
    defaultHealing: 4,
    healing: 4,
    cost: 2,
    defaultTurns: 2,
    turns: 2,
    ability: "",
    img: "./src/img/treeOfVitality.png",
    id: 3,
  },
  {
    name: "Tree of Vitality",
    defaultHealing: 4,
    healing: 4,
    cost: 2,
    defaultTurns: 2,
    turns: 2,
    ability: "",
    img: "./src/img/treeOfVitality.png",
    id: 4,
  },
  {
    name: "Hound",
    defaultAttack: 3,
    attack: 3,
    cost: 1,
    defaultTurns: 2,
    turns: 2,
    ability: "",
    img: "./src/img/hound.png",
    id: 5,
  },
  {
    name: "Hound",
    defaultAttack: 3,
    attack: 3,
    cost: 1,
    defaultTurns: 2,
    turns: 2,
    ability: "",
    img: "./src/img/hound.png",
    id: 6,
  },
  {
    name: "Castle Guardian",
    defaultAttack: 4,
    attack: 4,
    cost: 2,
    defaultTurns: 2,
    turns: 2,
    ability: "",
    img: "castleDefender.png",
    id: 7,
  },
  {
    name: "Castle Guardian",
    defaultAttack: 4,
    attack: 4,
    cost: 2,
    defaultTurns: 2,
    turns: 2,
    ability: "",
    img: "castleDefender.png",
    id: 8,
  },
  {
    name: "Caplan of Miridith",
    defaultHealing: 5,
    healing: 5,
    cost: 3,
    defaultTurns: 2,
    turns: 2,
    ability: "",
    img: "./src/img/caplanOfMiridith.png",
    id: 9,
  },
  {
    name: "Caplan of Miridith",
    defaultHealing: 5,
    healing: 5,
    cost: 3,
    defaultTurns: 2,
    turns: 2,
    ability: "",
    img: "./src/img/caplanOfMiridith.png",
    id: 10,
  },
  {
    name: "Strong farmer",
    defaultAttack: 4,
    attack: 4,
    cost: 3,
    defaultTurns: 2,
    turns: 2,
    ability: "",
    img: "./src/img/strongFarmer.png",
    id: 11,
  },
  {
    name: "Strong farmer",
    defaultAttack: 4,
    attack: 4,
    cost: 3,
    defaultTurns: 2,
    turns: 2,
    ability: "",
    img: "./src/img/strongFarmer.png",
    id: 12,
  },
  {
    name: "Berserker",
    defaultAttack: 7,
    attack: 7,
    cost: 4,
    defaultTurns: 1,
    turns: 1,
    ability: "",
    img: "./src/img/berserker.png",
    id: 13,
  },
  {
    name: "Berserker",
    defaultAttack: 7,
    attack: 7,
    cost: 4,
    defaultTurns: 1,
    turns: 1,
    ability: "Rage",
    img: "./src/img/berserker.png",
    id: 14,
  },
  {
    name: "King's Defender",
    defaultAttack: 4,
    attack: 4,
    cost: 4,
    defaultTurns: 3,
    turns: 3,
    ability: "",
    img: "./src/img/kingsDefender.png",
    id: 15,
  },
  {
    name: "King's Defender",
    defaultAttack: 4,
    attack: 4,
    cost: 4,
    defaultTurns: 3,
    turns: 3,
    ability: "",
    img: "./src/img/kingsDefender.png",
    id: 16,
  },
  {
    name: "Military Hornist",
    defaultAttack: 3,
    attack: 3,
    cost: 4,
    defaultTurns: 3,
    turns: 3,
    ability: "Rage",
    img: "./src/img/militaryHornist.png",
    id: 17,
  },
  {
    name: "Military Hornist",
    defaultAttack: 3,
    attack: 3,
    cost: 4,
    defaultTurns: 3,
    turns: 3,
    ability: "Rage",
    img: "./src/img/militaryHornist.png",
    id: 18,
  },
  {
    name: "Light of Azhura",
    defaultHealing: 5,
    healing: 5,
    cost: 5,
    defaultTurns: 3,
    turns: 3,
    ability: "Blessing",
    img: "./src/img/lightOfAzhura.png",
    id: 19,
  },
  {
    name: "Light of Azhura",
    defaultHealing: 5,
    healing: 5,
    cost: 5,
    defaultTurns: 3,
    turns: 3,
    ability: "Blessing",
    img: "./src/img/lightOfAzhura.png",
    id: 20,
  },
  {
    name: "Firandil the Bloody",
    defaultAttack: 6,
    attack: 6,
    cost: 5,
    defaultTurns: 3,
    turns: 3,
    ability: "Rage",
    img: "./src/img/firandilTheBloody.png",
    id: 21,
  },
  {
    name: "Burning Horse",
    defaultAttack: 7,
    attack: 7,
    cost: 5,
    defaultTurns: 2,
    turns: 2,
    ability: "",
    img: "./src/img/BurningHorse.png",
    id: 22,
  },
  {
    name: "Burning Horse",
    defaultAttack: 7,
    attack: 7,
    cost: 5,
    defaultTurns: 2,
    turns: 2,
    ability: "",
    img: "./src/img/BurningHorse.png",
    id: 23,
  },
  {
    name: "Time traveler",
    defaultAttack: 3,
    attack: 3,
    cost: 5,
    defaultTurns: 2,
    turns: 2,
    ability: "Hourglass",
    img: "./src/img/timeTraveler.png",
    id: 24,
  },
  {
    name: "Time traveler",
    defaultAttack: 3,
    attack: 3,
    cost: 5,
    defaultTurns: 2,
    turns: 2,
    ability: "Hourglass",
    img: "./src/img/timeTraveler.png",
    id: 25,
  },
  {
    name: "Ciril the Mighty",
    defaultAttack: 7,
    attack: 7,
    cost: 7,
    defaultTurns: 4,
    turns: 4,
    ability: "",
    img: "./src/img/cirilTheMighty.png",
    id: 26,
  },
  {
    name: "Archmage Valorian",
    defaultAttack: 6,
    attack: 6,
    cost: 7,
    defaultTurns: 5,
    turns: 5,
    ability: "",
    img: "./src/img/archmageValorian.png",
    id: 27,
  },
  {
    name: "Princess Laurith",
    defaultHealing: 7,
    healing: 7,
    cost: 7,
    defaultTurns: 3,
    turns: 3,
    ability: "Blessing",
    img: "./src/img/princessLaurith.png",
    id: 28,
  },
  {
    name: "Karcoth The King",
    defaultAttack: 8,
    attack: 8,
    cost: 8,
    defaultTurns: 4,
    turns: 4,
    ability: "",
    img: "./src/img/karcothTheKing.png",
    id: 29,
  },
  {
    name: "Azhura",
    defaultAttack: 8,
    attack: 8,
    cost: 9,
    defaultTurns: 3,
    turns: 3,
    ability: "Hourglass",
    img: "./src/img/azhura.png",
    id: 30,
  },
];
